  
"  __    _
" |  \  | | Dem Nikos seine config
" |   \ | | vim
" | |\ \| | Just some basic vim functionality
" |_| \___| Communism will win
set expandtab
set ignorecase
set incsearch
set encoding=utf-8
set linebreak
syntax enable
set number relativenumber
set nu rnu
set noswapfile
